/*!
 * ***********************************
 * @ldesign/editor-core v3.0.0     *
 * Built with rollup               *
 * Build time: 2024-10-30 16:01:17 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */
// Placeholder for WebAssembly Base64 data
// This file will be generated by running: npm run build:wasm
// Source: diff.wat
// To generate, run: node scripts/build-wasm.js
var diff_wasm_base64 = '';

export { diff_wasm_base64 as default };
/*! End of @ldesign/editor-core | Powered by @ldesign/builder */
//# sourceMappingURL=diff.wasm.base64.js.map
