/*!
 * ***********************************
 * @ldesign/editor-core v3.0.0     *
 * Built with rollup               *
 * Build time: 2024-10-30 16:01:17 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

// Placeholder for WebAssembly Base64 data
// This file will be generated by running: npm run build:wasm
// Source: parser.wat
// To generate, run: node scripts/build-wasm.js
var parser_wasm_base64 = '';

exports.default = parser_wasm_base64;
/*! End of @ldesign/editor-core | Powered by @ldesign/builder */
//# sourceMappingURL=parser.wasm.base64.cjs.map
